Add member image for Myron Zhou
ctc-uci/commit-the-change-website pull request #309
Opened 2022-10-20 00:54 UTC by MyronZhou0

2022-10-26 05:05 UTC, claudeisakeeb requested changes
Hi Myron, for this task you're also supposed to make changes in members.js to actually add your picture to your NPO page. Could you re-request review when those changes are pushed?

2022-10-30 23:17 UTC, alanchangxyz commented
^ bumping, message either me or Claude if you need help finishing this up

2022-10-31 02:21 UTC, alanchangxyz commented
can you fix merge conflicts then re-request review - you can ask one of us if you need help doing that

2022-10-31 05:01 UTC, claudeisakeeb requested changes
Almos there, could you fix these changes and then re-request review?

2022-10-31 05:01 UTC, claudeisakeeb commented on website/src/app/views/our-team/members.js
> +        linkedinURL: 'linkedin.com/in/myron-zhou-a98270238',
Change this to "https://..." or else it links to localhost

2022-11-01 03:35 UTC, claudeisakeeb approved these changes
Looks great, good job Myron

2022-11-01 03:35 UTC, merged