Added member photo/info for Kainoa Nishida
ctc-uci/commit-the-change-website pull request #314
Opened 2022-10-20 16:06 UTC by ctc-devops

Authors:
 ### What does this PR contain?
 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #290

2022-10-21 05:26 UTC, alanchangxyz commented
not sure if this is actually ready or not but looks like no changes have been pushed yet, make sure you've got your local version of your branch and the github version synced up with `git push` (git will give you additional instructions if you've never pushed the branch to github before)

2022-10-21 14:49 UTC, KainoaNishida commented
> not sure if this is actually ready or not but looks like no changes have been pushed yet, make sure you've got your local version of your branch and the github version synced up with `git push` (git will give you additional instructions if you've never pushed the branch to github before)

> okay I think I did it! my local branch should be pushed to the github version.

2022-10-21 15:02 UTC, claudeisakeeb requested changes
Changes look good, just 2 small issues and this PR should be good to go

2022-10-21 15:02 UTC, claudeisakeeb commented on website/src/app/views/our-team/members.js
> +      {
Members should be displayed in ascending alphabetical order. Could you move your picture to the right spot?

2022-10-21 15:02 UTC, claudeisakeeb commented on website/src/app/views/our-team/members.js
> +import kainoa from '../../../images/ourTeam/memberImages/kainoa.jpeg';
Could you delete the unused "kainoa.jpg"?

2022-10-21 23:50 UTC, KainoaNishida commented on website/src/app/views/our-team/members.js
> +import kainoa from '../../../images/ourTeam/memberImages/kainoa.jpeg';
Okay! I went back and did some edits and hopefully its all good now

2022-10-22 04:34 UTC, alanchangxyz approved these changes
as the tech bros say, LGTM

2022-10-22 04:34 UTC, merged