Modified members.js and added an image in order to display Kevin Liu …
ctc-uci/commit-the-change-website pull request #322
Opened 2022-10-21 06:45 UTC by kevnlliu

…as a developer for Patriots and Paws

2022-10-21 14:59 UTC, claudeisakeeb requested changes
Changes look good, just one reordering issue and this PR should be good to go

2022-10-21 14:59 UTC, claudeisakeeb commented on website/src/app/views/our-team/members.js
> +      {
Members should be shown in ascending alphabetical order. Could you move your picture to the right spot?

2022-10-21 21:11 UTC, alanchangxyz requested changes
yeah what claude said + pls fix merge conflicts + your pr title shouldn't be this long LOL (you can move the full thing to the description and make the title something short like `Add member info/photo for Kevin Liu`)

2022-11-06 22:12 UTC, claudeisakeeb approved these changes
Looks great! LGTM

2022-11-06 22:13 UTC, merged